package io.github.lord1egypt.prootx.support

import com.squareup.moshi.JsonClass

/**
 * Parsed `assets/support/metadata/support-map.json`, generated by the build-time
 * `prepareProotXSupport` task from the validated v1.2.0 routing/manifest contract.
 *
 * This is the single runtime source of truth for support routing. No code may infer
 * lanes or filenames from names such as `.a10` or `lib_proot`.
 */
@JsonClass(generateAdapter = true)
data class SupportMap(
    val schemaVersion: Int,
    val release: String,
    val supportedAbis: List<String>,
    val common: List<CommonFile>,
    val abis: Map<String, SupportAbi>
) {
    fun abi(name: String): SupportAbi =
        abis[name] ?: throw SupportMapException("support map has no ABI '$name'")
}

@JsonClass(generateAdapter = true)
data class CommonFile(
    val name: String,
    val assetPath: String,
    val sha256: String,
    val executable: Boolean
)

@JsonClass(generateAdapter = true)
data class SupportAbi(
    val legacy: List<LegacyFile>,
    val modern: List<ModernFile>
)

@JsonClass(generateAdapter = true)
data class LegacyFile(
    val name: String,
    val assetPath: String,
    val sha256: String,
    val executable: Boolean
)

@JsonClass(generateAdapter = true)
data class ModernFile(
    val name: String,
    val nativeLib: String,
    val sha256: String
)

class SupportMapException(message: String) : IllegalStateException(message)
